name: states_rebuilder_extended
description: "Extensions and helpers enhancing states_rebuilder (Injected) API: update/toggle/multi-builder utilities + MyNull injector."
version: 1.0.0
homepage: https://github.com/SoundSliced/states_rebuilder_extended
repository: https://github.com/SoundSliced/states_rebuilder_extended
issue_tracker: https://github.com/SoundSliced/states_rebuilder_extended/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  states_rebuilder: ^7.0.0-dev1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
